# Generated by Django 2.2.5 on 2019-09-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Runcolors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=128, null=True)),
                ('product_number', models.CharField(blank=True, max_length=256, null=True)),
                ('product_name', models.CharField(blank=True, max_length=256, null=True)),
                ('price_regular', models.FloatField(blank=True, null=True)),
                ('price_now', models.FloatField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=512, null=True)),
                ('url_jpg', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'db_table': 'runcolors',
                'managed': False,
            },
        ),
    ]
